# Generated by Django 3.1.2 on 2020-11-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettingsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_owner', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Bot Settings',
            },
        ),
        migrations.CreateModel(
            name='SdcSettingsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdc_path', models.CharField(max_length=30)),
                ('sdc_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'SDC Settings',
            },
        ),
        migrations.CreateModel(
            name='ServerSettingsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_server_id', models.CharField(max_length=200)),
                ('prefix', models.CharField(max_length=30)),
                ('points_name', models.CharField(max_length=30)),
                ('bot_owner', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Server Settings',
            },
        ),
        migrations.CreateModel(
            name='SimpleDiscordCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('brief', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('output', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Simple Discord Commands',
            },
        ),
    ]
