# Generated by Django 3.0.5 on 2020-11-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mage_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serversettingsmodel',
            name='bot_owner',
        ),
        migrations.RemoveField(
            model_name='serversettingsmodel',
            name='discord_server_id',
        ),
        migrations.RemoveField(
            model_name='serversettingsmodel',
            name='prefix',
        ),
        migrations.AddField(
            model_name='serversettingsmodel',
            name='bot_prefix',
            field=models.CharField(default='!', max_length=5),
        ),
    ]
